const state={rows:[],latest:null,dataFile:null,sort:{key:null,dir:-1}};
const fmt=(v,d=1)=>v==null||Number.isNaN(v)?'n.d.':new Intl.NumberFormat('it-IT',{minimumFractionDigits:0,maximumFractionDigits:d}).format(v);
const n=v=>{if(typeof v==='number')return v;if(v==null||v===''||String(v).toLowerCase()==='s.v.')return null;const x=Number(String(v).replace(',','.'));return Number.isFinite(x)?x:null};
const clean=v=>String(v??'').trim();
const yes=v=>clean(v).toUpperCase()==='SI'||clean(v).toUpperCase()==='SÌ';
const group=(arr,key)=>arr.reduce((a,r)=>((a[r[key]]??=[]).push(r),a),{});
function normalizeRow(r){return{giornata:n(r.Giornata),squadra:clean(r.Squadra),modulo:clean(r.Modulo),giocatore:clean(r.Giocatore),ruolo:clean(r.Ruolo).toUpperCase(),voto:n(r.Voto),fantavoto:n(r.Fantavoto),bonus:n(r.BonusMalus)??0,titolare:yes(r.Titolare),votoUtile:yes(r.VotoUtile),sostituisce:clean(r.Sostituisce),vdm:n(r['VdM (mln €)'])}}
async function parseArrayBuffer(buf,name){if(!window.XLSX)throw new Error('Libreria Excel non disponibile. Verifica la connessione internet.');const wb=XLSX.read(buf,{type:'array'});if(!wb.SheetNames.includes('Database'))throw new Error('Il file non contiene il foglio “Database”.');const raw=XLSX.utils.sheet_to_json(wb.Sheets.Database,{defval:null});const rows=raw.map(normalizeRow).filter(r=>r.giornata&&r.squadra&&r.giocatore);if(!rows.length)throw new Error('Nessuna riga valida trovata nel foglio Database.');state.rows=rows;state.latest=Math.max(...rows.map(r=>r.giornata));state.dataFile=name;renderAll();}
async function importFile(file){setStatus('Lettura del file…');try{await parseArrayBuffer(await file.arrayBuffer(),file.name);setStatus('Dati aggiornati correttamente',true)}catch(e){setStatus(e.message,false,true)}}
function setStatus(text,ok=false,error=false){document.getElementById('statusText').textContent=text;document.querySelector('.status-dot').style.background=error?'#c64f4b':ok?'#249b60':'#dfa70a'}
function bonusAnalysis(){return Object.entries(group(state.rows,'squadra')).map(([team,rs])=>{const vu=rs.filter(r=>r.votoUtile),role=x=>vu.filter(r=>r.ruolo===x).reduce((s,r)=>s+r.bonus,0);return{Squadra:team,'Portieri (VU)':role('P'),'Difensori (VU)':role('D'),'Centrocampisti (VU)':role('C'),'Attaccanti (VU)':role('A'),'Totale Voti Utili':vu.reduce((s,r)=>s+r.bonus,0),Subentrati:rs.filter(r=>!r.titolare&&r.votoUtile).reduce((s,r)=>s+r.bonus,0),'Panchinari (no P)':rs.filter(r=>!r.titolare&&!r.votoUtile&&r.ruolo!=='P').reduce((s,r)=>s+r.bonus,0)}}).sort((a,b)=>a.Squadra.localeCompare(b.Squadra,'it'))}
function vdmAnalysis(){return Object.entries(group(state.rows,'squadra')).map(([team,rs])=>{const days={};rs.filter(r=>r.votoUtile&&r.vdm!=null).forEach(r=>days[r.giornata]=(days[r.giornata]||0)+r.vdm);const vals=Object.values(days);return{team,days,avg:vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:null,last:days[state.latest]??null}})}
function renderTable(el,data){if(!data.length){el.innerHTML='';return}const cols=Object.keys(data[0]);let rows=[...data];if(state.sort.key)rows.sort((a,b)=>{const x=a[state.sort.key],y=b[state.sort.key];return (typeof x==='string'?x.localeCompare(y,'it'):(x??-Infinity)-(y??-Infinity))*state.sort.dir});el.innerHTML=`<thead><tr>${cols.map(c=>`<th data-key="${c}">${c}${state.sort.key===c?(state.sort.dir>0?' ↑':' ↓'):''}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${cols.map(c=>`<td class="${typeof r[c]==='number'?(r[c]>0?'positive':r[c]<0?'negative':''):''}">${typeof r[c]==='number'?(r[c]>0?'+':'')+fmt(r[c],2):r[c]}</td>`).join('')}</tr>`).join('')}</tbody>`;el.querySelectorAll('th').forEach(th=>th.onclick=()=>{const key=th.dataset.key;state.sort.dir=state.sort.key===key?-state.sort.dir:-1;state.sort.key=key;renderTable(el,data)})}
function renderRank(el,data,key){el.innerHTML=data.filter(x=>x[key]!=null).sort((a,b)=>b[key]-a[key]).map((x,i)=>`<div class="rank-row"><span class="rank-pos">${i+1}</span><span class="rank-team">${x.team}</span><span class="rank-value">${fmt(x[key],1)} mln €</span></div>`).join('')}
function renderDashboard(){document.getElementById('latestMatchday').textContent=`Giornata ${state.latest}`;renderTable(document.getElementById('bonusTable'),bonusAnalysis());const v=vdmAnalysis();renderRank(document.getElementById('avgRank'),v,'avg');renderRank(document.getElementById('lastRank'),v,'last');document.getElementById('lastRankLabel').textContent=`Giornata ${state.latest}`;document.getElementById('vdmCaption').textContent=`Aggiornato alla G${state.latest}`}
function teamStats(team){const rs=state.rows.filter(r=>r.squadra===team),vu=rs.filter(r=>r.votoUtile),role=x=>vu.filter(r=>r.ruolo===x),sum=a=>a.reduce((s,r)=>s+r.bonus,0),avg=(a,k)=>{const q=a.map(r=>r[k]).filter(x=>x!=null);return q.length?q.reduce((x,y)=>x+y,0)/q.length:null};const subs=rs.filter(r=>!r.titolare&&r.votoUtile),bench=rs.filter(r=>!r.titolare&&!r.votoUtile&&r.ruolo!=='P');const byPlayer=Object.entries(group(vu,'giocatore')).map(([name,a])=>({name,role:a[0].ruolo,fv:avg(a,'fantavoto'),bonus:sum(a),vdm:a.find(x=>x.vdm!=null)?.vdm??null,pres:a.length}));const top=[];[['P',1],['D',3],['C',4],['A',3]].forEach(([role,count])=>top.push(...byPlayer.filter(x=>x.role===role&&x.fv!=null).sort((a,b)=>b.fv-a.fv||b.bonus-a.bonus).slice(0,count)));const days={};vu.filter(r=>r.vdm!=null).forEach(r=>days[r.giornata]=(days[r.giornata]||0)+r.vdm);const vals=Object.values(days);return{rs,metrics:[['Portieri',sum(role('P')),avg(role('P'),'voto')],['Difensori',sum(role('D')),avg(role('D'),'voto')],['Centrocampisti',sum(role('C')),avg(role('C'),'voto')],['Attaccanti',sum(role('A')),avg(role('A'),'voto')],['TOTALE',sum(vu),avg(vu,'voto')],['Subentrati',sum(subs),avg(subs,'voto')],['Panchinari (no P)',sum(bench),avg(bench,'voto')]],days,vdm:{avg:vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:null,max:vals.length?Math.max(...vals):null,min:vals.length?Math.min(...vals):null,last:days[state.latest]??null},top}}
function renderTeam(team){const s=teamStats(team);document.getElementById('teamTitle').textContent=team;document.getElementById('teamSubtitle').textContent=`G${state.latest} · analisi voti utili e valore di mercato`;document.getElementById('teamMetrics').innerHTML=`<thead><tr><th>Reparto</th><th>Bonus/Malus</th><th>Media voto</th></tr></thead><tbody>${s.metrics.map(r=>`<tr class="${r[0]==='TOTALE'?'total-row':''}"><td>${r[0]}</td><td class="${r[1]>0?'positive':r[1]<0?'negative':''}">${r[1]>0?'+':''}${fmt(r[1],1)}</td><td>${fmt(r[2],2)}</td></tr>`).join('')}</tbody>`;document.getElementById('vdmKpis').innerHTML=[['Media VdM',s.vdm.avg],['Max',s.vdm.max],['Min',s.vdm.min],['Ultima g.',s.vdm.last]].map(x=>`<div class="kpi"><b>${fmt(x[1],1)}</b><span>${x[0]}</span></div>`).join('');renderPitch(s.top);renderTopTable(s.top);drawChart(s.days,s.vdm.avg)}
function renderPitch(top){const coords={P:[[50,90]],D:[[23,73],[50,73],[77,73]],C:[[14,49],[38,49],[62,49],[86,49]],A:[[22,23],[50,23],[78,23]]};const used={P:0,D:0,C:0,A:0},pitch=document.getElementById('pitch');pitch.querySelectorAll('.player').forEach(x=>x.remove());top.forEach(p=>{const c=coords[p.role][used[p.role]++];const el=document.createElement('div');el.className=`player role-${p.role}`;el.style.left=c[0]+'%';el.style.top=c[1]+'%';el.innerHTML=`<div class="player-ball">${fmt(p.fv,1)}</div><div class="player-name" title="${p.name}">${p.name}</div>`;pitch.appendChild(el)});const avg=top.length?top.reduce((s,p)=>s+p.fv,0)/top.length:null,bonus=top.reduce((s,p)=>s+p.bonus,0),vdm=top.reduce((s,p)=>s+(p.vdm||0),0);document.getElementById('topSummary').textContent=`Media FV Top 11: ${fmt(avg,2)}  |  Bonus/Malus: ${bonus>0?'+':''}${fmt(bonus,1)}  |  VdM: ${fmt(vdm,1)} mln €`}
function renderTopTable(top){const tAvg=top.length?top.reduce((s,p)=>s+p.fv,0)/top.length:null,tBonus=top.reduce((s,p)=>s+p.bonus,0),tPres=top.reduce((s,p)=>s+p.pres,0),tVdm=top.reduce((s,p)=>s+(p.vdm||0),0);document.getElementById('top11Table').innerHTML=`<thead><tr><th>Ruolo</th><th>Giocatore</th><th>Media Fantavoto</th><th>Bonus/Malus</th><th>Presenze utili</th><th>VdM</th></tr></thead><tbody>${top.map(p=>`<tr><td>${p.role}</td><td>${p.name}</td><td>${fmt(p.fv,2)}</td><td class="${p.bonus>0?'positive':p.bonus<0?'negative':''}">${p.bonus>0?'+':''}${fmt(p.bonus,1)}</td><td>${p.pres}</td><td>${fmt(p.vdm,1)} mln €</td></tr>`).join('')}</tbody><tfoot><tr><td colspan="2">TOTALE</td><td>${fmt(tAvg,2)}</td><td class="${tBonus>0?'positive':tBonus<0?'negative':''}">${tBonus>0?'+':''}${fmt(tBonus,1)}</td><td>${tPres}</td><td>${fmt(tVdm,1)} mln €</td></tr></tfoot>`}
function drawChart(days,mean){const c=document.getElementById('vdmChart'),dpr=devicePixelRatio||1,w=c.clientWidth,h=c.clientHeight;c.width=w*dpr;c.height=h*dpr;const x=c.getContext('2d');x.scale(dpr,dpr);x.clearRect(0,0,w,h);const entries=Object.entries(days).map(([a,b])=>[+a,b]).sort((a,b)=>a[0]-b[0]);if(!entries.length)return;const pad={l:45,r:18,t:20,b:34},vals=entries.map(e=>e[1]),min=Math.min(...vals)*.9,max=Math.max(...vals)*1.08,px=i=>pad.l+i*(w-pad.l-pad.r)/Math.max(1,entries.length-1),py=v=>pad.t+(max-v)*(h-pad.t-pad.b)/(max-min||1);x.font='11px Segoe UI';x.fillStyle='#637083';x.strokeStyle='#d8e2ef';for(let i=0;i<4;i++){const v=min+(max-min)*i/3,y=py(v);x.beginPath();x.moveTo(pad.l,y);x.lineTo(w-pad.r,y);x.stroke();x.fillText(fmt(v,0),3,y+4)}if(mean!=null){x.strokeStyle='#dfa70a';x.beginPath();x.moveTo(pad.l,py(mean));x.lineTo(w-pad.r,py(mean));x.stroke()}x.strokeStyle='#3577b9';x.lineWidth=3;x.beginPath();entries.forEach((e,i)=>i?x.lineTo(px(i),py(e[1])):x.moveTo(px(i),py(e[1])));x.stroke();entries.forEach((e,i)=>{x.fillStyle='#173f70';x.beginPath();x.arc(px(i),py(e[1]),5,0,Math.PI*2);x.fill();x.fillStyle='#173f70';x.textAlign='center';x.fillText(fmt(e[1],1),px(i),py(e[1])-10);x.fillStyle='#637083';x.fillText('G'+e[0],px(i),h-10)});x.textAlign='left'}
function renderAll(){document.getElementById('emptyState').classList.add('hidden');document.querySelectorAll('.page').forEach((p,i)=>p.style.display='');document.getElementById('fileMeta').textContent=`${state.dataFile} · ${state.rows.length.toLocaleString('it-IT')} righe`;renderDashboard();const teams=[...new Set(state.rows.map(r=>r.squadra))].sort((a,b)=>a.localeCompare(b,'it')),sel=document.getElementById('teamSelect'),current=teams.includes(sel.value)?sel.value:teams[0];sel.innerHTML=teams.map(t=>`<option${t===current?' selected':''}>${t}</option>`).join('');renderTeam(current)}
function showEmpty(msg){document.querySelectorAll('.page').forEach(p=>p.style.display='none');document.getElementById('emptyState').classList.remove('hidden');setStatus(msg||'Importa un file Excel per iniziare',false,true)}
document.querySelectorAll('.nav-btn').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav-btn').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===b.dataset.page));if(b.dataset.page==='squadre'&&state.rows.length)renderTeam(document.getElementById('teamSelect').value)});document.getElementById('fileInput').onchange=e=>e.target.files[0]&&importFile(e.target.files[0]);document.getElementById('emptyFileInput').onchange=e=>e.target.files[0]&&importFile(e.target.files[0]);document.getElementById('teamSelect').onchange=e=>renderTeam(e.target.value);addEventListener('resize',()=>{if(state.rows.length&&document.getElementById('squadre').classList.contains('active'))renderTeam(document.getElementById('teamSelect').value)});
(async()=>{try{const r=await fetch('F2627_Risultati_e_analisi.xlsx');if(!r.ok)throw 0;await parseArrayBuffer(await r.arrayBuffer(),'F2627_Risultati_e_analisi.xlsx');setStatus('File iniziale caricato',true)}catch(e){showEmpty(location.protocol==='file:'?'Apri la webapp tramite un server locale o importa manualmente il file Excel.':'Importa un file Excel per iniziare.')}})();
